sudo: false
language: node_js
node_js:
  - "11"
  - "10"
  - "9"
  - "8"

install:
  - npm install -g npm@latest
  - npm install
  - npm run bootstrap:ci

script:
  - npm run lint
  - npm run test
  - npm run build

notifications:
  email: false
