swagger: '2.0'
info:
  title: Cloud Endpoints - Cloud Functions
  description: API Endpoints to Support Development of Crystallography API
  version: 1.0.0
  contact:
    email: "vreshch@gmail.com"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
host: crystallography-api-6q6gddw3pa-ew.a.run.app
basePath: /api/v1

schemes:
  - https

produces:
  - application/json

paths:
  /structures:
    get:
      summary: "Get a list of Structures"
      operationId: Get-Structures-List
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "page"
          in: "query"
          type: "number"
          description: "Page Number"
          required: false
      x-google-backend:
        address: https://europe-west1-crystallography-api.cloudfunctions.net/api-get-structures-list
      responses:
        '200':
          description: A successful response
          schema:
            type: string
        '400':
          description: Invalid Param Provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      required:
          - errors
      errors:
        type: array
        items:
          $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
        - code
        - message
        - details
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        details:
          type: string
