name: Deploy Containers

on:
  push:
    branches:
      - master
    paths:
      - 'packages/containers/**'

jobs: # Jobs List
  deploy:
    name: Deploy Cloud Function
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
            version: '270.0.0'
            service_account_email: ${{ secrets.GCP_SA_EMAIL }}
            service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Check Google Cloud
        run: gcloud info && gcloud auth configure-docker -q
      - name: Install dependencies
        run: npm ci && npm run bootstrap:ci
      - name: Verify build
        run: npm run lint && npm run test
      - name: Build & Push
        run: ./scripts/build-and-psuh-containers.sh
